# Project-wide Gradle settings.

# Enable AndroidX
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX (just in case)
android.enableJetifier=true

# Faster builds
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.suppressUnsupportedCompileSdk=35
android.aapt2.override=/usr/local/bin/aapt2
android.suppressUnsupportedCompileSdk=35
